name: progress_dialog
description: A light weight library to easily manage a progress dialog with simple steps whenever you need to do it. You can easily show and hide it.
version: 1.2.4
author: Aiden_Pearce<salmanah8551@gmail.com>
homepage: https://github.com/ansari-salman/progress_dialog

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/double_ring_loading_io.gif

